# Streamlit Secrets Configuration Template
# Copy this to .streamlit/secrets.toml and add your actual API key

[general]
# Add your Gemini API key here for cloud deployment
GEMINI_API_KEY = "your-gemini-api-key-here"

# Optional: Add other service keys if needed
# OPENAI_API_KEY = "your-openai-key-here"
# ANTHROPIC_API_KEY = "your-anthropic-key-here"